// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import './src/config/load-env.js';
import { defineConfig } from 'prisma/config';
import { resolveMigrationDatabaseUrl } from './src/config/database-url.js';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: resolveMigrationDatabaseUrl(),
  },
});
